name: "Deploy Web App to QA"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      
env:
  AZURE_WEBAPP_NAME: github-user-lookup 
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

jobs:
  
  build-and-test:
    name: 🧪 Build and Test Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.x', '18.x']
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, build, and test
      run: |
        # Build and test the project
        npm install
        npm run build --if-present
        npm run test --if-present

  prettier:
    name: 🧹 Pretty Up Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --write **/*.{js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linter:
    name: 🧹 Lint Code
    runs-on: ubuntu-latest
    needs: [prettier, build-and-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

  webapp-deploy-validate:
    name: 📦 Deploy Code to Validate
    runs-on: ubuntu-latest
    needs: [build-and-test, prettier]
    environment:
      name: validate
      url: "https://${{ env.AZURE_WEBAPP_NAME }}-validate.azurewebsites.net/"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: |
        npm install
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: validate
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3.1
      with:
        # Check the following URLs one by one sequentially
        url: https://${{ env.AZURE_WEBAPP_NAME }}-sandbox.azurewebsites.net/|https://${{ env.AZURE_WEBAPP_NAME }}-sandbox.azurewebsites.net/user/rob-derosa
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s

  webapp-deploy-qa:
    name: 📦 Deploy Code to QA
    runs-on: ubuntu-latest
    needs: [webapp-deploy-validate]
    environment:
      name: qa
      url: "https://${{ env.AZURE_WEBAPP_NAME }}-qa.azurewebsites.net/"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: |
        npm install
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: qa
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3.1
      with:
        # Check the following URLs one by one sequentially
        url: https://${{ env.AZURE_WEBAPP_NAME }}-qa.azurewebsites.net/|https://${{ env.AZURE_WEBAPP_NAME }}-qa.azurewebsites.net/user/rob-derosa
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
